package channel;

/**
 * An abstract class that represents an event generated by a channel
 */
public abstract class ChannelEvent {

    private final short id;

    /**
     * Create a channel event with the given id
     * @param id the numeric identifier of the channel event
     */
    public ChannelEvent(short id){
        this.id = id;
    }

    public short getId() {
        return id;
    }
}